# Generated by Django 4.0.5 on 2022-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saves',
            name='unique_user_Product',
        ),
        migrations.AddConstraint(
            model_name='saves',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product'),
        ),
    ]
