# Generated by Django 4.0.5 on 2022-08-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0002_remove_saves_unique_user_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsearch',
            name='ip_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
