# Generated by Django 4.0.5 on 2022-08-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0003_newsearch_ip_address_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
